version: '3.8'

services:
  app:
    build: .
    container_name: forum_app
    restart: unless-stopped
    volumes:
      - db-data:/root/data
    expose:
      - "8080"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/letsencrypt/live/localhost
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

volumes:
  db-data:
